insert
	into
	"Med_Appointments" ("date",
	doctor_id,
	location_id)
values
	 ('2022-08-03',
1,
1),
	 ('2022-08-04',
1,
1),
	 ('2022-08-06',
1,
1);

insert
	into
	"Med_Doctor" ("name",
	specialization,
	monday_hours,
	tuesday_hours,
	wednesday_hours,
	thursday_hours,
	friday_hours,
	monday_location,
	tuesday_location,
	wednesday_location,
	thursday_location,
	friday_location)
values
	 ('Jan Kowalski',
'Okulista',
'8:00 - 17:00',
'9:00 - 12:00',
'8:00 - 17:00',
'8:00 - 17:00',
'-',
'Centrum medyczne Centrum',
'Centrum medyczne Bemowo',
'Centrum medyczne Centrum',
'Centrum medyczne Centrum',
'-'),
	 ('Joanna Nowak',
'Internista',
'9:00 - 12:00',
'9:00 - 12:00',
'9:00 - 12:00',
'9:00 - 12:00',
'8:00 - 17:00',
'Centrum medyczne Wilanów',
'Centrum medyczne Wilanów',
'Centrum medyczne Wilanów',
'Centrum medyczne Wilanów',
'Centrum medyczne Rembertów');

insert
	into
	"Med_Location" ("name",
	address_line_1,
	address_line_2,
	phone_number,
	description)
values
	 ('Centrum medyczne Wilanów',
'ul. Wilanowska 17',
'01-234 Warszawa',
'+48 123 456 789',
'Placówka specjalistyczna oferująca ofertę specjalistów ze specjalizacją: alergolog, okulista, pediatra, neurolog'),
	 ('Centrum medyczne Bemowo',
'ul. Bemowska 133',
'01-111 Warszawa',
'+48 123 456 789',
'Placówka specjalistyczna oferująca ofertę specjalistów ze specjalizacją: alergolog, okulista, pediatra, neurolog'),
	 ('Centrum medyczne Rembertów',
'ul. Rembertowska 14',
'01-789 Warszawa',
'+48 123 456 789',
'Placówka specjalistyczna oferująca ofertę specjalistów ze specjalizacją: alergolog, okulista, pediatra, neurolog'),
	 ('Centrum medyczne Centrum',
'ul. Centralna 100/12',
'01-001 Warszawa',
'+48 123 456 789',
'Placówka specjalistyczna oferująca ofertę specjalistów ze specjalizacją: alergolog, okulista'),
	 ('Centrum medyczne Mokotów',
'ul. Nowa 13',
'01-156 Warszawa',
'+48 000 000 000',
'Nowa placówka otwarta w 2022 roku');

insert
	into
	"Med_Pages" ("name",
	description,
	img_link,
	bg_color,
	text_color,
	"order")
values
	 ('Placówki na terenie całej Warszawy',
'Nasze placówki oferują szeroką gamę badań i zabiegów na terenie całej Warszawy',
null,
'#0d7916',
'#FFFFFF',
1),
	 ('Szybka pomoc',
'Sprawdź wolne terminy badań w zakładce umów wizytę',
null,
'#61a355',
'#FFFFFF',
2);

insert
	into
	"Med_Reservation" (appointment_id,
	"name",
	surname,
	patient_phone_num,
	is_reserved,
	"hour",
	couse,
	patient_email)
values
	 (1,
null,
null,
null,
false,
'13:00',
null,
null),
	 (1,
null,
null,
null,
false,
'20:00',
null,
null),
	 (4,
null,
null,
null,
false,
'08:00',
null,
null),
	 (1,
'Łukasz',
'Czarny',
'+48234567899',
true,
'10:00',
'',
'l.czarny@mail.com'),
	 (1,
'Łukasz',
'Czarny',
'+48123456789',
true,
'14:00',
'Testowa przyczyna',
'aaaa@mail.com'),
	 (2,
'',
'',
'',
false,
'09:00',
'',
''),
	 (1,
'',
'',
'',
false,
'12:00',
'',
'');
